### ISSUE TITLE
Contraxt context information

### ISSUE THREAD

**Issue by Yhtiyar** [bugout-dev/moonstream#10]
Getting function call information of smart contracts is hard task, however for now we can only show basic information about contract such as:
* Name of contract (If it is known for us)
* Link to source code (If it is known for us)
* ABI of smart contract
* Estimated gas 

Probably I will use python to easily integrate to API. 
Ready solutions to use:
* https://github.com/beched/abi-decompiler - Does the abi decompilation, but it is written in python2, probably I need to rewrite it in python3. 
* https://github.com/MrLuit/evm - this is easy to use, also decodes events, but it is in JS
* https://github.com/palkeo/panoramix - very powerful with great decoder, ,but it requires to run in eth node (I think it gets data from storage). [example](https://oko.palkeo.com/0x06012c8cf97BEaD5deAe237070F9587f8E7A266d/calls_from/) 

UPD:
I crawled function and event signatures from https://www.4byte.directory/. Now we can decode ABI of smart contract bytecode

**Comment by zomglings** [comment]
@Yhtiyar : 

For alpha, we will only use ABI decompilation information (using Ethereum Signature Database).

We will use the Etherscan crawl data and GitHub crawl data in subsequent releases.

For now, the priority is on defining the library interface to ABI decompilation information and hooking it up to the API.
