### ISSUE TITLE
Backend v0

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#12]
@Andrei-Dolgolev : Coordinage with @peersky to understand what endpoints he needs on the backend.

Coordinate with @kompotkot to understand how to read data from blockchain database.

Coordinate with @Yhtiyar to understand how to expose smart contract decompilation metadata to @peersky on the frontend.

**Comment by zomglings** [comment]
@Andrei-Dolgolev , @kompotkot : I suggest to create a `db/` folder in which we define models and alembic migrations for the blockchain database.

Folder structure:
```
moonstream
|-- frontend
|-- backend
|-- db
|-- crawlers
    |-- ethereum
    |-- etherscan
```

**Comment by Andrei-Dolgolev** [comment]
Add subscription limit on create `subscriptions`
