### ISSUE TITLE
Whale watch improvement

### ISSUE THREAD

**Issue by peersky** [bugout-dev/moonstream#173]
We want to make Whale Watch feature more easy to use. For that we want to implement following: 

- [x] New Subscription modal should not ask for `address` and `name` for whale watch 
- [ ] Backend should not allow to create more then one whale watch per token
- [x] #175
- [ ] We should provision that whale watch cards can be subscribed to different sources... Speaking in terms of whales, we can call this - `oceans`. That is platforms or protocols - ethereum, or twitter etc

**Comment by zomglings** [comment]
Oceans will be handled by new subscription types.

For now, we won't add backed protection for multiple whale watch subscriptions.
