### ISSUE TITLE
Casing on addresses should not matter in lookups

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#248]
Currently all addresses are being stored as EIP-55 checksum addresses.

This causes problems for lookups if a user created a subscription using an all lowercase address.

There are a few ways to fix this:
1. Checksum all addresses before storing them in subscriptions
2. Store checksummed and lowercase and uppercase addresses in database/humbug journal
3. Lowercase all addresses for comparison

Not clear what the best way forward is, but we need to fix the issue.

**Comment by kompotkot** [comment]
Fixed with PR https://github.com/bugout-dev/moonstream/pull/349
