### ISSUE TITLE
Alpha frontend metatags

### ISSUE THREAD

**Issue by peersky** [bugout-dev/moonstream#6]
We need to fill up following metatags: 

### Landing page ###
```
title: ""
description: ""
keywords:  ""
url: ""
image: ""
```

**Comment by zomglings** [comment]
My proposal:
### Landing page ###
```
title: "Moonstream.to"
description: "All the crypto data you need, in one stream"
keywords:  "blockchain", "crypto", "data", "trading", "smart contracts", "ethereum", "solana", "transactions", "defi", "finance", "decentralized"
url: "https://www.moonstream.to"
image: ""
```

Image should be either logo (moth on moon) or Harriatte's landing page image.

**Comment by SophiaAr** [comment]
title: Moonstream.to: All your crypto data in one stream
description: From the Ethereum transaction pool to Elon Musk’s latest tweets get all the crypto data you care about in one stream.
keywords:  "blockchain", "crypto", "data", "trading", "smart contracts", "ethereum", "solana", "transactions", "defi", "finance", "decentralized"
"https://www.moonstream.to"
image: moth on moon
