### ISSUE TITLE
First round of feedback on Moonstream frontend

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#61]
## Transaction hashes

Would be nice to see transaction hashes on the cards in the stream. These are quite commonly used to verify that you're looking at the right transaction (across sites, from Javascript console, etc.). It should be prominent.

(Currently, only shows up in transaction details.)

## Colors

Cards feel a little too colorful. Would prefer that colors are used to display information about subscriptions only. Rest of the card can be white or dark depending on theme.

Examples to consider:
1. @kompotkot : Suggested this site - https://dribbble.com/search/card%20component%20list
2. @Andrei-Dolgolev : liked this for minimalism - https://dribbble.com/shots/15221832/attachments/6968098?mode=media
3. @zomglings : Likes the GitHub repository cards that show up in Slack - 
![image](https://user-images.githubusercontent.com/8016073/128212848-149edfc7-9f97-4adb-9ca5-0658e65f9246.png)

## Transaction details should not take over full view

Would be nice to be able to switch between transactions when looking at details. This could be similar to entries list vs. entries on [Bugout frontend](https://bugout.dev).

@kompotkot can fill in more details if this ever becomes confusing.

**Comment by Nadria** [comment]
I created a password with a space in it during registration but the error message said the password is too short even though that was not the problem. Once I removed the space - it let me register.

If you fill in the registration form, click the show password "eye" button and highlight your password - the registration pop up closes.

It's a small thing but maybe I should mention - the moonstream logo on the upper left of the landing page is clickable but doesn't lead anywhere. 
![image](https://user-images.githubusercontent.com/88392948/128223281-a7a6a658-cc51-4a53-a5fb-3b68b931b410.png)
Also, the moth logo seems a bit big to me - it's so close to the border that it creates an unwanted focal point (compare it to the ant logo in bugout - it's very far from borders).
