### ISSUE TITLE
Stream pagination

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#63]
For streams, it makes sense to paginate based on time rather than based on a cursor, IDs, etc.

Pagination requests can have the following form:

```json
{
    "start_time": "1628093198",
    "end_time": "1628093524",
    "include_start": true,
    "include_end": null,
    "limit": 10
}
```

Pulls at most the first 10 entries in the stream from the backend starting at the `"start_time"` and ending at the `"end_time"`.

Response format:

```json
{
    "data": "[<at most 10 entries>]",
    "next_start_time": "null or <if there is an 11th entry, timestamp for 11th entry>"
}
```

**Comment by zomglings** [comment]
If 10th and 11th entries have same start time, what do we do?

**Comment by Andrei-Dolgolev** [comment]
Add 1 hour as default  limit for data.

Remove infinitQuery()

**Comment by zomglings** [comment]
## Example of `stream_boundary` update

User's current stream boundary:

```json
{
    "start_time": 1628093198,
    "end_time": 1628093524,
    "include_start": true,
    "include_end": false,
    "next_event_time": 1628093600,
    "previous_event_time": 1628093000
}
```

Say the user loads 5 more minutes of data using a request with these pagination parameters:

```json
{
    "start_time": 1628093524,
    "end_time": 1628095524,
    "include_start": true,
    "include_end": true,
}
```

Suppose API response is:
```json
{
    "start_time": 1628093198,
    "end_time": 1628093524,
    "include_start": true,
    "include_end": true,
    "next_event_time": 1628097023,
    "previous_event_time": 1628092000
}
```

Then the new stream boundary should be:
```json
{
    "start_time": 1628093198,
    "end_time": 1628093524,
    "include_start": true,
    "include_end": true,
    "next_event_time": 1628097023,
    "previous_event_time": 1628093000
}
```

**Comment by zomglings** [comment]
Instead of storing stream boundary in the cache, we decided to store it as react state. It makes more sense and is easier to use.

@Andrei-Dolgolev : We should probably add it to the `UIProvider` instead of defining it directly in the `useStream` hook.

**Comment by zomglings** [comment]
Already present in production and we have been updating this in recent pull requests.
