### ISSUE TITLE
No more hung rollbacks!

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#717]
We are seeing too many production errors on Moonstream crawlers and API that look like this:

```
sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: https://sqlalche.me/e/14/8s2b)
```

([SQLAlchemy documentation on error details](https://docs.sqlalchemy.org/en/14/errors.html#error-8s2b))

We should go through the code, `git grep ".commit("` and make sure that we are correctly handling exceptions and rolling back transactions *everywhere*.

**Comment by Andrei-Dolgolev** [comment]
closed https://github.com/bugout-dev/moonstream/pull/727
