### ISSUE TITLE
Update README to reflect current state of product

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#729]
The current readme for this repo presents an outdated view of our product and misrepresents its goals. We should update this to be consistent with our landing page.

**Comment by daria-bochkareva** [comment]
[Suggestions in Google doc](https://docs.google.com/document/d/16j82N1eFYOSN2FKLy4H_gqzK_4Q9bnXPpnB8gV-71dg/edit?usp=sharing)

**Comment by daria-bochkareva** [comment]
https://github.com/bugout-dev/moonstream/pull/730#pullrequestreview-1208380085
