### ISSUE TITLE
Better onboarding experience required

### ISSUE THREAD

**Issue by zomglings** [bugout-dev/moonstream#78]
Currently, when a user registers for an account, they see a blank streams screen.

The easiest thing we can do for now is implement a modal which explains the product to them and how they can use it which only shows up when they first log in and is later accessible through a `?` icon on the navbar.

When a new user visits the subscriptions screen, there is no explanation of what a subscription is or how it works. We need more guidance here for the user, perhaps also through a modal. Maybe we can make the `?` contextual?

**Comment by peersky** [comment]
Created User flow diagram 
https://miro.com/app/board/o9J_l2XMvOI=/

**Comment by zomglings** [comment]
Suggested onboarding state:

```json
{
    "subscriptions": true,
    "stream": false,
    "api": true
}
```

Frontend can deploy with an array of available onboarding:
```json
[
    {"step": "subscriptions", "description": "Learn how to subscribe to blockchain events"},
    {"step": "stream", "description": "Learn how to use your Moonstream to analyze blah blah blah"},
    {"step": "api", "description": "Learn how to use the Moonstream API to access your stream from your programs"}
]
```

**Comment by zomglings** [comment]
@zomglings : Create content for first onboarding pages:

0. Welcome to Moonstream (documentation index)
1. Subscriptions
2. Stream
3. API
